# Generated by Django 3.0.5 on 2020-04-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='department',
        ),
    ]
