# Generated by Django 3.0.5 on 2020-05-01 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_remove_temperature_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='temp',
            new_name='temp_AM',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='time_temp_taken',
        ),
        migrations.AddField(
            model_name='temperature',
            name='temp_PM',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date_temp_taken',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
