# Generated by Django 3.0.5 on 2020-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20200501_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date_temp_taken',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temp_AM',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
