# Generated by Django 3.0.5 on 2020-05-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20200502_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temp_AM',
            field=models.DecimalField(decimal_places=2, default=36, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temp_PM',
            field=models.DecimalField(decimal_places=2, default=36, max_digits=4),
        ),
    ]
