# Generated by Django 3.0.5 on 2020-05-11 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20200511_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date_temp_taken',
            field=models.DateField(default=datetime.datetime.now, unique=True),
        ),
    ]
