# Generated by Django 3.0.5 on 2020-05-23 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20200511_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='onboard',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date_temp_taken',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temp_PM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='temperature',
            unique_together={('user', 'date_temp_taken')},
        ),
    ]
